package com.rp.automation.framework;

public enum WaitType {
    WAIT_FOR_ELEMENT_TO_BE_ENABLED,
    WAIT_FOR_ELEMENT_TO_BE_DISPLAYED,
    WAIT_FOR_ELEMENT_TO_BE_CLICKABLE,
    WAIT_FOR_ELEMENT_TO_DISAPPEAR,
    WAIT_FOR_FRAME_TO_BE_DISPLAYED
}
